# Org mode outline of PlanetMath Activities   -*- mode: Org; -*-
#+TODO: LOW MEDIUM HIGH TODO | DONE 
* Overview (to sort, current conversations)
** Top priorities for programming
*** TODO [#A] Produce some downloadable snapshots of the content on a regular basis
    SCHEDULED: <2013-11-09 Sat>
Send to Murray
*** TODO [#A] Front page improvements to follow up with Ray and Murray
    SCHEDULED: <2013-11-09 Sat>
*** HIGH MSC Browser cache
** Finish the first demo books
** Collections of Topic Articles
** Calculus book preparation
** Catalog to develop a clear sense of what's out there (contact David King and Jim Pitman)
*** "What free math is there?"
*** Decide our license procedure
*** What can we do on top of Wikipedia and StackExchange content?  (E.g. interactive/dynamic.)
** Import Project Gutenburg books
* Capacity Building Discussion and Strategies
** Realistic estimates of time commitment
*** Joe: 2-10 hours per week
**** 2 hour  . . . PM community interaction
**** 5 hours . . . Planetary (do logging to figure out how much time it takes to close an average ticket)
**** Development: goals
    - at least 52 tickets (what are the top tickets?)
**** Income: goals
    - $2000 bounties (funded by CivicRM)
*** Ray: according to 2014 schedule
**** 8 hours . . . PM community interaction
**** 4 hours . . . PM administration and outreach
**** 4 hours . . . Teaching a class or two
**** 4 hours . . . Building maintenance and repair
**** 20 hours . . . Research and development
**** Income: goals
    - $5400 teaching ($45/class * 30 classes/qtr * 4 qtr/yr)
    - $6600 PM Operations Manager (20% of $33,000/yr)
*** Aaron: hopefully something to push forward the business end
**** Experiences with blog stuff on Implode/Explode: bloggers can build big followings
*** Deyan: in concert with Ph. D.
*** Advisory board: ask them about other people who can do content or coding: can we get a student doing undergrad study once a semester?
**** Include other known academics who have been members of the site
**** Offering mentorship and experience: you could be developing cutting edge math on the web content and technology
**** Structure it so you don't depend too much on any one intern
*** High school or college intern?
** technical issues: let's keep debugging a little at a time.
https://github.com/holtzermann17/planetmath-docs (organization level)
https://github.com/kwarc/planetary (technical issues)
*** some of the technical issues will take place on a recurrent basis
**** medium update the drupal core and contributed modules with security fixes :monthly:
*** some pressing priorities in order to move things forward at all
**** todo [#a] upload stuff to existing collections.               :importer:
     scheduled: <2013-10-17 thu>
**** todo [#a] take an existing node, and adjust the content.      :importer:
     scheduled: <2013-11-09 sat>
**** medium generally, keep a (potentially large) collection of articles up to date. :importer:
** let's continue to try to get some more institutional support for this stuff.
i can imagine quickly getting out of my depth, so i want
to be realistic about that -- at the same time, i also want to be
realistic about (a) what sort of institutional support would help (as
well as (b) what sort of institutional support would be possible).
*** hire a professional programmer to do some work on the site.
«the problem is that the demand for drupal talent exceeds the supply.
as such, most of the drupal developers i know are maxed out.»
http://buytaert.net/on-hiring-drupal-talent
if we had money, we'd probably end up hiring someone like florian
lengyel, and, with due respect, i don't know for sure that he knows
more about this stuff than me.  rather than putting all our eggs in
one basket (a given lead dev), i think the issue should have more to
do with building the skills of the team.
here, i think you're on the right track with reading a few books!  but
what else can we do here?
*** put priority on features which are actively being used.  
for instance, if the hott thing takes
off, then prioritize bug fixes and improvements which
affect how the book displays and the like.
i agree.  i think we're using the github tracker well.  we can ping
the latexml developers as well -- they are reasonably active in
bugfixing, so we can get support on those issues.
*** put priority on work which makes it easier to gain contributors
examples include documentation, cleaning up, and making things easier to install.
yes - maybe we need to allocate a certain number of weekly hours to
these things.  for instance, if we always meet on saturday, we could
allocate n hours before and n hours after the meeting to this sort of
stuff.
*** promote planetary and try to get organizations to try it out and use it. 
for instance, should glen whitney come to the conclusion that planetary
and/or planetmath were useful for running the math museum, quite likely
he'd pay florian lengyel to work on it.  other candidates
include springer and the n-cat lab.  we should find time
to contact them or, if we're not ready yet, figure out
exactlly what else needs to be done to planetary to put
it into a shape which is worth promoting and prioritize
those improvements.  i did write to florian, but he didn't write back yet.  in
general i agree with this priority -- sounds like maybe rather than a
weekly cycle, we need a monthly cycle here.  can we add this to your
monthly agenda?
** start some new projects
*** start planetcomputing. 
that's a tall order, we've talked about it for some years, but it could help in bringing in
coders.  right now, in new york, i am seeing the tech community growing by leaps and bounds and think that there is a niche for something like this, providing we don't wait for someone else to do it first.
otoh, simply creating a new drupal instance for us to use to document
things as we go would be very easy.  it might not immediately take
off, but at least we'd know where we were putting our documentation -
and it would be actively in use as long as we and other planetary devs
were using it.

along those lines, i am noting a rapidly growing interest
in the intersection of math and computers among the functional
programming community.  thus, i want to be sure to get back
to hdm stuff and keep at least a foot in that door lest we
get lost on the wyside as forgotten pioneers.  one of the
things i am hoping to do today and tomorrow is to pose pm as
a place for discussions and work on this topic.
*** revive planetphysics.
porting this into planetary would be a good idea, putting under the
planetmath umbrella would be ok.  contact ben to discuss and get
latest snapshot of pp.

** let's make use of our own "premium" advertising space to advertise what we're actually doing
**** todo 250 word summary and links to previews on the site
**** todo civicrm configuration on the beta test site
* Monthly schedule
** Blog the news items (i.e. short summaries of the meetings)
** 1st Saturday of month --- Community discussion
reviving what i did back in the good old days
of pm, but with a new medium.  this would be
a bottom-up, grassroots opportunity for members
of the pm community to meet each other and
discuss topics of mutual interest, give feedback,
and raise concerns and suggestions,
*** October 5, preparing this schedule
** 2nd Saturday of month --- Developer discussion

a chance to get together and discuss the codebase
of planetary, nnexus, and friends.
**** TODO what are the top 52 tickets (buy a deck of cards or use arxana for that)?
*** October 12, planned the slice/dice/upload system to work this week
** 3rd Saturday of month --- Business meeting
Like today, a structured meeting with an agenda to set the course of
the organization for the upcoming month, review progress, and handle
any issues which arise.  we could have every third such meeting
automatically be the quarterly board meeting.
**** TODO [#a] advisory board note and nuffield foundation overture :outreach:

     scheduled: <2013-10-19 sat>
**** DONE [#a] report back on org mode, schedule board mtg              :org:
     closed: [2013-11-11 mon 00:55] scheduled: <2013-10-19 sat>
     - closing note [2013-11-11 mon 00:55] \\
       the standard board meeting is scheduled.  we'll need to schedule the
       advisory board meeting as well but that can be handled separately.
       org mode seems to be working well, and i hope i can use it with other
       projects!
**** medium update the planetmath "linear schedule" as the frame shifts forward
** 4th Saturday of month --- Math meeting

Something like our old NRI meetings or lispnyc meetups; each one
starts with a presentation by one of the members on some mathematical
topic of interest, followed by a discussion of that topic which may
move into other areas deppending on the interest of the attendees.
*** December 28, meeting to discuss Arxana/HONEY
*** January 25, invite people like John Awbrey?
** 5th Saturday of month --- Big picture strategy!
*** December 30th, look at plans for the next 3 years for different PlanetMath participants and others
Invite Charlie, Charlotte, Helene?
* Linear schedule
** November
*** Initial docs import and new blurb for front page
*** First half of CiviCRM (set up email, payment methods, and so forth)
*** Get blog systems working: at least design and pseudocode level, probably finish it
*** Top Tickets
***** 
** December
*** Graphs research and development
*** Finish working with CiviCRM and launch it
*** One more book, work on course material (e.g. Hardy's book and our math textbook)
*** Top Tickets
***** 
** January
*** Likely: Run a first class
*** Somewhat less likely: Work on the wikimedia grant
*** Advisory board meeting for January
*** Top Tickets
***** 
** February
*** Grant follow up stuff
*** Top Tickets
***** 
** March
*** With money: this may make it very clear (e.g. Wikipedia stuff) 
*** And without much money: reconsider our strategy based on data
*** Top Tickets
***** 
* Relatively current discussions and activities - to act on and complete sometime this autumn
** Exports for BABAR
This is a reminder to please provide dumps of attached entries and keywords.  Don't worry about the format, just use whatever is most convenient since I will massage it into the proper format for uptake into BABAR and tidy it up.
** Homotopy type theory
AS I mentioned, I think that this group which is
meeting in New York is a wonderful opportunity for
PM.  Their next meeting is during the first week of
October and I hoping we can have most of the
following in place by then.
*** HOTT book online
*** Exercises from book
*** HOTT collection
*** HOTT forum
** Relaunch
Even if we haven't finished everything we hope to, I
nevertheless think that it would be worthwhile to have
some sort of a site relaunch sometime in October. 
*** Q/A/Problem/Solution section
*** Collections
*** Books (HOTT and PG)
*** Course
*** Technical issues
**** TODO Assigning collections to another author :feature:
There is a "work around" (the feature works, but only works for admin
users).
*** Personally contact past collaborators and top users.
** Course
Since this week has been hectic with unrelated house work,
I didn't get a chance to put together the announcement for
the course; I will attend to that in the upcoming week.
Because of all the other things going on, because preparing
the textbook has turned out to be more time-consuming
than anticipated, and because it is already the middle of
September, I am thinking of instead scheduling the course
for the first quarter of 2014 and putting out the announcement
and registration along with the relaunch.
** Advisory board
Once the dust settles from all these other items, it might
be time to reconvene our advisory board.  I like what you
are doing; for instance, we might tell them that it would
cost 20000 Euros to fix up the Drupal and that there is a
EU grant which could pay for this providing that we can come
up with 5000 Euros on our end and work through a European
organization, then see what Michael and everyone else come
up with.  In general, I think that starting the discussion
with such concrete data and suggestions should keep us from
again floating about in vague proposals and platitudes about
attracting more volunteers and the like.
** Bibliographies project
Following up what you sent about bibliographies in Planetary,
I would like to sort out the different things related to
bibliographies into a coherent plan.  I am thinking that we
could get in touch with Pitman and with the fellow at OU to
see how things are going with BKN and figure out where we
fit in to this scheme of things
** Following up with PlanetMath Books Exchange grant proposal
Contact Wikiversity and Wikibkooks people to ask them what would be
useful for them and look into collaboration with PM and FKN on course
projects.  Contact past/present PM users who who were/are involved
with WP.

* Grant applications
** Can we match our previews up with funding agencies?
*** What's next for Planetary preview
Immediate wish is to raise €11K ($15K USD) to pay programmers, can we find a foundation that would help with that? 
*** Books
We've made some progress on this
*** Bibliography 
*** Classroom 
Ray is working on the calculus book and will try to launch in Spring (has a business model so we don't necessarily need to apply for grants here)
*** Projects 
Write something for Christoph about this - to send to EU?... and connect it with "computer math"
Starting HoTT, hyperbolic geometry, resistor networks and the like as ad hoc projects using existing software.
*** Internationalization
*** Computer Math 
*** Experimental Math 
*** Hypertext & Metamath
*** "Indie Bundle"
*** "Making other business models work"
https://github.com/holtzermann17/planetmath-docs/wiki/Business-Models
*** Patronage
Joe can be working on hooking up the CivicRM software

** Funding institutions to follow up with
*** General ideas
We can be a center for the development of online tools, we've proven
our ability to develop things without much funding.  We can do things
that need to be done for math online, peer learning, social computing
-- without being too entrenched.
*** Wikimedia Foundation
http://www.wikimedia.org/
we've proposed a version of the Books preview here
Rolling schedule, so can resubmit after getting feedback.
They have several different "flavors" of grants we can apply for, see https://meta.wikimedia.org/wiki/Grants:Start
**** We have an application under consideration, and that's a good thing
And we've gotten some feedback, https://meta.wikimedia.org/wiki/Grants_talk:IEG/PlanetMath_Books_Project#Aggregated_feedback_from_the_committee_for_PlanetMath_Books_Project
*** Nuffield Foundation
http://www.nuffieldfoundation.org
Does do capacity building grants, mainly interested in organizations
based in the UK...
http://www.nuffieldfoundation.org/capacity-building

They are also specifically interested in mathematics education:
http://www.nuffieldfoundation.org/mathematics-education

http://www.nuffieldfoundation.org/mathematics-education-0 here's some
more info about their work in this area.

They might be interested in our Classroom preview?  Also, since they
are not opposed to capacity building, they might be interested in
addressing some of the core issues in our Strategic Plan at the top of
this document.

The contact person is Kim Woodruff, kwoodruff@nuffieldfoundation.org

Their address is: Nuffield Foundation, 28 Bedford Square, London, WC1B
3JS (near the Goodge Street tube stop)
**** HIGH Make an appointment with Kim Woodruff

*** Simons Foundation
https://www.simonsfoundation.org/
*** European Union
http://ec.europa.eu/governance/impact/planned_ia/docs/2013_eac_003_opening_up_education_en.pdf
(pre-plan about the "Opening Up Education")

*** Shuttleworth Foundation
http://www.shuttleworthfoundation.org/
*** Mellon Foundation
http://www.mellon.org/
http://www.mellon.org/news_publications/annual-reports-essays/presidents-essays/priorities-for-the-scholarly-communications-program priorities
http://www.mellon.org/grant_programs/programs/scit
Letters of inquiry should be brief, extending no more than three
pages.  The letter should describe: the project for which you are
seeking funding; its scope, objectives, and significance; why you
require external funding and what benefits you would achieve from such
funding; the specific activities for which funding is being requested;
and how much funding is needed.

«(1) to support libraries and archives in their efforts to preserve
and provide access to materials of broad cultural and scholarly
significance; (2) to assist scholars in the development of specialized
resources that promise to open or advance fields of study in the
humanities and humanistic social sciences; and (3) to strengthen the
publication of humanistic scholarship and its dissemination to the
widest possible audience.»

Accordingly, I'm not sure whether mathematics is really something they
can support -- we could send them a VERY short email asking about
this.  Some of their stuff about cultural and scholarly work would be
relevant (assuming they think of mathematics as "cultural", which I
do!).

http://www.brynmawr.edu/math/people/melvin/ a mathematician whos work
was supported by the Mellon foundation (potentially worth an email to
ask him about this)

Other (somewhat related) precedent:
https://www.wm.edu/as/charlescenter/mellon/index.php

*** ArXiv
http://arXiv.org
I sent a note to simeon warner
**** Note from Gowers: http://episciences.org/ is setting up a platform for running overlay journals

*** Springer
http://www.springer.com

*** NSF
*** Bechtel
http://www.bechtel.com/foundation.html
I sent them a quick query via their contact form, haven't heard back

*** National Endowment for the Humanities
http://www.neh.gov

*** Gabriella & Paul Rosenbaum Foundation
http://www.rosenbaum-foundation.org/
Generally interested in mathematics, they seem to require letters of interest be sent to Madge Rosenbaum Goldman, 764 Mt. Pleasant Road, Bryn Mawr, PA 19010
I think we should put together a 2-to-3 page letter to send to them.
*** The Number Theory Foundation
http://www.math.uiuc.edu/ntf/
Looks like they mainly do conference funding
